# Generated by Django 2.2.6 on 2020-01-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('books_count', models.IntegerField()),
                ('isbn', models.CharField(blank=True, max_length=100)),
                ('isbn13', models.CharField(max_length=100)),
                ('authors', models.CharField(blank=True, max_length=150)),
                ('original_publication_year', models.IntegerField()),
                ('original_title', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('language_code', models.CharField(blank=True, max_length=10)),
                ('average_rating', models.FloatField(default=2.5, max_length=5)),
                ('ratings_count', models.IntegerField()),
                ('image_url', models.CharField(blank=True, max_length=100)),
                ('small_image_url', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['-average_rating'],
            },
        ),
    ]
